spring.application.name=Vue3 Spring Project

spring.datasource.url=jdbc:postgresql://localhost:5432/hit_scope
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
